== Spring Data Repositories

=== CRUD Operations

=== CRUD Operations

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String> {

}
----

[source, language="java"]
----
@Autowired
private StarbucksStoreRepository starbucksStoreRepository;

...
private final StarbucksStore starbucksStore = new StarbucksStore();
starbucksStore.setId("1");
...
    starbucksStoreRepository.save(starbucksStore);
    starbucksStoreRepository.save(storeCollection)
    starbucksStoreRepository.delete(starbucksStore);
    starbucksStoreRepository.delete("1");
    starbucksStoreRepository.deteleAll();
    final Long count = starbucksStoreRepository.count();
    final StarbucksStore foundStore = starbucksStoreRepository.findOne("1");
    final Collection<StarbucksStore> stores = starbucksStoreRepository.findAll();
...
----


=== Creating Queries

=== Creating Queries

[source, language="java"]
----
@SolrDocument
public class StarbucksStore {
   @Id
   @Field("id")
   private String id;
   @Field("name")
   private String name;
   @Field("zipCode")
   private String zipCode;
   @Field("city")
   private String city;
   @Field("street")
   private String street;
   @Field("products")
   private Collection<String> products;
   @Field("services")
   private Collection<String> services;
   @Field("location")
   private Point location;
}
----

=== Creating from Method Names

=== Find By Name

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String>{

    /**
     * find stores by name
     *
     * @param name the name of store
     * @return a collection of stores, where the input match
     */
    Collection<StarbucksStore> findByName(final String name);


}
----

----
    q=name: ?0
----

=== Find By Name

[source, language="java"]
----

@Autowired
private StarbucksStoreRepository starbucksStoreRepository;

...
    Collection<StarbucksStore> result = starbucksStoreRepository.findByName("Boston");
...
----

----
    q=name: 'Boston'
----

=== Find By Products

=== Find By Products

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String>{

    /**
     * find all stores whoch provides the given products
     *
     * @param products products query parameter
     * @return a collection of stores, where the input match
     */
     Collection<StarbucksStore> findByProductsIn(final Collection<String> products);

}
----

----
    q=products:(?0…​ )
----


=== Find By Products

[source, language="java"]
----

@Autowired
private StarbucksStoreRepository starbucksStoreRepository;

...
    final Collection<String> products = new LinkedList<>();
    products.add("food");
    products.add("lunch");

    Collection<StarbucksStore> result = starbucksStoreRepository.findByProductsIn(products);
...

----

----
q=products:('food' 'lunch')
----

=== Find By Location

=== Find By Location

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String>{
     /**
     * find all stores which provides the given products and are
     * next to a geo point and given distance
     *
     * @param products products query parameter
     * @param point    geo location
     * @param distance radius distance to the geo point
     * @return a collection of stores, where the input match
     */
    Collection<StarbucksStore> findByProductsInAndLocationNear(final Collection<String> products,
                                                               final Point point,
                                                               final Distance distance);
}
----

----
    q=products:(?0…​ ) AND {!bbox pt=?0.latitude,?0.longitude sfield=location d=?1}
----

=== Find By Location

[source, language="java"]
----
@Autowired
private StarbucksStoreRepository starbucksStoreRepository;
    ...
    final Collection<String> products = new LinkedList<>();
    products.add("food");
    products.add("lunch");

    final Point point = new Point(72D, -42D);
    final Distance distance = new Distance(100D);

    Collection<StarbucksStore> result = starbucksStoreRepository
                        .findByProductsInAndLocationNear(products,point,distance);
    ...

----

----
    q=products:('food' 'lunch') AND {!bbox pt=72,-42 sfield=location d=100}
----

=== Creating from Method Names

|====

|And|findByNameAndPopularity|q=name:?0 AND popularity:?1
|Or |findByNameOrPopularity |q=name:?0 OR popularity:?1
|Is|findByName|q=name:?0
|Not|findByNameNot|q=-name:?0
|IsNull |findByNameIsNull|q=-name:[* TO *]
|IsNotNull|findByNameIsNotNull|q=name:[* TO *]
|Between| findByPopularityBetween|q=popularity:[?0 TO ?1]
|LessThan|findByPopularityLessThan|q=popularity:[* TO ?0}

|====


=== Creating from Method Names

|====

|LessThanEqual|findByPopularityLessThanEqual|q=popularity:[* TO ?0]
|GreaterThan|findByPopularityGreaterThan|q=popularity:{?0 TO *]
|GreaterThanEqual|findByPopularityGreaterThanEqual|q=popularity:[?0 TO *]
|Before|findByLastModifiedBefore|q=last_modified:[* TO ?0}
|After|findByLastModifiedAfter|q=last_modified:{?0 TO *]
|Like|findByNameLike|q=name:?0*
|NotLike|findByNameNotLike|q=-name:?0*
|StartingWith|findByNameStartingWith|q=name:?0*

|====

=== Creating from Method Names

|====

|EndingWith|findByNameEndingWith|q=name:*?0
|Containing|findByNameContaining|q=name:*?0*
|Matches|findByNameMatches|q=name:?0
|In|findByNameIn(Collection<String> names)|q=name:(?0…​ )
|NotIn|findByNameNotIn(Collection<String> names)|q=-name:(?0…​ )
|Within|findByStoreWithin(Point, Distance)|q={!geofilt pt=?0.latitude,?0.longitude sfield=store d=?1}
|Near|findByStoreNear(Point, Distance)|q={!bbox pt=?0.latitude,?0.longitude sfield=store d=?1}

|====

=== Creating from Method Names

|====

|Near|findByStoreNear(Box)|q=store[?0.start.latitude,?0.start.longitude TO ?0.end.latitude,?0.end.longitude]
|True|findByAvailableTrue|q=inStock:true
|False|findByAvailableFalse|q=inStock:false
|OrderBy|findByAvailableTrueOrderByNameDesc|q=inStock:true&sort=name desc

|====

=== Using @Query

=== Find By Name

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String>{

  /**
  * find stores by name
  *
  * @param name the name of store
  * @return a collection of stores, where the input match
  */
  @Query("name:?0")
  Collection<StarbucksStore> findByNameQuery(final String name);

}
----

=== Filter Queries

=== Find By Name

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String>{

    /**
     * find stores by name
     *
     * @param name the name of store
     * @return a collection of stores, where the input match
     */
    @Query(value = "*:*", filters = {"name:=?0"})
    Collection<StarbucksStore> findByNameFilterQuery(@Param("name") final String name);

}
----

----
    q=*:*&fq=name:?0
----

=== Faceting

=== Facets of all Products

[source, language="java"]
----
public interface StarbucksStoreRepository extends SolrCrudRepository<StarbucksStore, String>{

    /**
     * find all stores
     *
     * @param page input page
     * @return a facet of the products of stores, where the input matches
     */
    @Query(value = "*:*")
    @Facet(fields = {"products"})
    FacetPage<StarbucksStore> findByFacetOnProducts(final Pageable page);

}
----

----
    q=*:*&facet.field=products
----

=== Facets of all Products
[source, language="java"]
----
@Autowired
private StarbucksStoreRepository starbucksStoreRepository;

....

final FacetPage<StarbucksStore> response = starbucksStoreRepository.findByFacetOnProducts(new
                PageRequest(0, 100));

final Page<FacetFieldEntry> facetResultPage = response.getFacetResultPage("products");

List<FacetFieldEntry> content = facetResultPage.getContent();

for (final FacetFieldEntry facetFieldEntry : content) {
     System.err.println("Found: " + facetFieldEntry.getValue());
}

....

----

=== Facets of all Products

----
Found: food
Found: oven
Found: warmed
Found: lunch
Found: espresso
Found: machine
Found: sirena
Found: amenity
Found: reserve
Found: batch
----


